### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by Exokyhh** [HollowHorizon/ResourceStages#1]
After installing this with GameStages, the mod crashes on startup, with this error:

[13:24:52] [Render thread/FATAL]: Mixin apply failed resourcestages.mixins.json:MinecraftMixin -> net.minecraft.client.Minecraft: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field pendingReload was not located in the target class net.minecraft.client.Minecraft. No refMap loaded.

[latest.log](https://github.com/HollowHorizon/ResourceStages/files/15234762/latest.log)

Am I supposed to run the game with just GameStages before, and after creating the stages, adding this mod? 

Forge - 43.3.0 
Version: 1.19.2

GameStages-Forge-1.19.2-11.1.5.jar
resourcestages-1.19.2-1.1.jar

**Comment by HollowHorizon** [comment]
Oh, the refmap didn't generate again.... Try fixed version: [ResourceStages 1.1.1](https://github.com/HollowHorizon/ResourceStages/releases/tag/latest-1.19.2). On CurseForge, there will be an update a little later

**Comment by HollowHorizon** [comment]
And you also forgot to install [KotlinForForge](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge).

**Comment by Exokyhh** [comment]
Yeah, didn't crash now

**Comment by Exokyhh** [comment]
Is KotlinForForge a dependency?

**Comment by Exokyhh** [comment]
Oh actually, it is installed

**Comment by Exokyhh** [comment]
![kotlin](https://github.com/HollowHorizon/ResourceStages/assets/90096585/cb244f27-41c2-4488-b4a5-dc9422d96b65)

**Comment by Exokyhh** [comment]
![kotlin](https://github.com/HollowHorizon/ResourceStages/assets/90096585/cb244f27-41c2-4488-b4a5-dc9422d96b65)

**Comment by HollowHorizon** [comment]
Yes, since the mod itself is written in Kotlin, you also need to install a library to support it. 
I take it the problem has been solved?

**Comment by Exokyhh** [comment]
Yes it loaded! But I found a new crash while testing the mod in-game, should I open another issue?

**Comment by Exokyhh** [comment]
I can write you on discord, maybe it's better?

**Comment by HollowHorizon** [comment]
All right, then let's do it that way
